### ISSUE TITLE
Einigung auf eine Sprache

### ISSUE THREAD

**Issue by cte4X** [CoderDojo-Saar/dojapp-saar#26]
Die Dateien, Variablen und branches sind immer entweder auf deutsch oder englisch, was etwas unschön ist. Welche Sprache würdet ihr vorschlagen? @andi1984 @DiabolusSon

**Comment by andi1984** [comment]
@cte4X Es ist leider so, dass ich beruflich rein in Englischer Sprache meine Nachrichten verfasse. Leider ist es mir einige Male passiert, dass ich _automatisch_ auch hier in Englisch geschrieben habe. Aber da wir hier nicht im Beruf sind und es so einfach zu verstehen sein soll wie möglich, würde ich sagen wir sollten Deutsch beibehalten und ich muss mich etwas zügeln in Englisch zu schreiben ;)

**Comment by cte4X** [comment]
Ich werde dann mal alles anpassen...

**Comment by cte4X** [comment]
Ich fände es ganz gut, wenn alles, was zu git gehört (also branches, labels, usw.), englisch bleiben/werden und Dateinamen, Variablen usw. deutsch.

**Comment by cte4X** [comment]
Okay, ich bin jetzt eher doch dafür, dass der Code (Variablen, Funktionen) englisch bleiben 😬

**Comment by andi1984** [comment]
@cte4X Okay, dann lass uns auf Englisch einigen. Für mich ist das natürlich in Ordnung. 👍
