### ISSUE TITLE
Nächsten CoderDojo Termin in eigenen Kalender eintragen

### ISSUE THREAD

**Issue by andi1984** [CoderDojo-Saar/dojapp-saar#29]
Idee: Den nächsten CoderDojo Termin per Buttonclick in den eigenen Kalender zu übernehmen.

**Comment by cte4X** [comment]
Hab zwei Möglichkeiten gefunden: 

1. https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin
2. https://github.com/carlsednaoui/add-to-calendar-buttons
