### ISSUE TITLE
Bildergalerie

### ISSUE THREAD

**Issue by andi1984** [CoderDojo-Saar/dojapp-saar#4]
Die App sollte eine Bildergalerie zum Durchstöbern enthalten.

**Comment by cte4X** [comment]
Fertiggestellt. Bilder müssen aber manuell geupdatet werden.
https://github.com/CoderDojo-Saar/dojapp-saar/blob/53ba1c832d6e11d6d7e33b5bd53976c9731fd7a2/bildergalerie.html#L55-L158
