### ISSUE TITLE
Sponsorenseite

### ISSUE THREAD

**Issue by andi1984** [CoderDojo-Saar/dojapp-saar#9]
Die App sollte einen Bereich zur Nennung der Sponsoren enthalten.

**Comment by cte4X** [comment]
Einen "Bereich" gibt es schon, eine extra Seite noch nicht.

**Comment by cte4X** [comment]
Die Seite ist fertig, die Sponsoren sind aber noch nicht eingetragen

**Comment by andi1984** [comment]
@cte4X PR hierfür ist raus (s. #13). Für das CoderDojo 5 ist die Sponsoreninfo irgendwie verloren gegangen. Werde ich noch herausfinden 👍

**Comment by cte4X** [comment]
Ist 5 noch auffindbar, oder kann das Issue geschlossen werden?

**Comment by kerstinreese** [comment]
Bei #5 gab es keinen Firmensponsor.

13, 12/2017, Uni
12, 11/2017, Testfabrik
11, 10/2017, eurodata
10, 09/2017, ÜberResearch
09, 06/2017, Hololux
08, 05/2017, Saarcamp
07, 04/2017, IMA
06, 03/2017, eurodata
05, 02/2017, - 
04, 01/2017, IKU Systems
03, 12/2016, Resolution
02, 11/2016, SQUILD
01, 10/2016, UberResearch
